spring.application.name=SKENGINEERING
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/SKENGINEERING
spring.datasource.username=root
spring.datasource.password=ranga818680@

#print the query on the console
spring.jpa.show-sql=true

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

#table is not avaliable then create a table(create)
spring.jpa.hibernate.ddl-auto=update
